import type { Metadata } from 'next';
import './globals.css';
import localfont from 'next/font/local';
import ThemeProvider from './components/ThemeProvider';

const googleSans = localfont({
  src: [
    {
      path: './fonts/ProductSans-Thin.ttf',
      weight: '100',
      style: 'normal',
    },
    {
      path: './fonts/ProductSans-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/ProductSans-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/ProductSans-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/ProductSans-Bold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/ProductSans-Black.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: 'bento.sntp',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={googleSans.className}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <div>{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
